---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-deployment
  labels:
    app: bookstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
        - name: bookstore-database
          image: mysql
          env:
            - name: MYSQL_DATABASE
              value: "user_ms"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "null"
          ports:
            - containerPort: 3306
        - name: bookstore-users
          image: app/user-service
          ports:
            - containerPort: 5000
        - name: bookstore-ui
          image: app/ui-service
          ports:
            - containerPort: 3000